apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '65536'
    machine.openshift.io/vCPU: '16'
  name: itzaro-rm5fyd6-td79l-worker-eastus1
  generation: 1
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: itzaro-rm5fyd6-td79l
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: itzaro-rm5fyd6-td79l
      machine.openshift.io/cluster-api-machineset: itzaro-rm5fyd6-td79l-worker-eastus1
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: itzaro-rm5fyd6-td79l
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: itzaro-rm5fyd6-td79l-worker-eastus1
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: itzaro-rm5fyd6
          publicLoadBalancer: itzaro-rm5fyd6-td79l
          userDataSecret:
            name: worker-user-data
          vnet: itzaro-rm5fyd6-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '1'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: itzaro-rm5fyd6-aro
          kind: AzureMachineProviderSpec
          location: eastus
          vmSize: Standard_D16as_v4
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: aro_410
            version: 410.84.20220125
          subnet: itzaro-rm5fyd6-worker-subnet
          apiVersion: machine.openshift.io/v1beta1
