apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '65536'
    machine.openshift.io/vCPU: '16'
  name: itzaro-rm5fyd6-td79l-odf-eastus4
  generation: 1
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: itzaro-rm5fyd6-td79l
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: itzaro-rm5fyd6-td79l
      machine.openshift.io/cluster-api-machineset: itzaro-rm5fyd6-td79l-odf-eastus4
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: itzaro-rm5fyd6-td79l
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: itzaro-rm5fyd6-td79l-odf-eastus4
        node-role.kubernetes.io/infra: ""
        cluster.ocs.openshift.io/openshift-storage: ""
    spec:
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 1024
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: itzaro-rm5fyd6
          publicLoadBalancer: itzaro-rm5fyd6-td79l
          userDataSecret:
            name: worker-user-data
          vnet: itzaro-rm5fyd6-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '1'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: itzaro-rm5fyd6-aro
          kind: AzureMachineProviderSpec
          location: eastus
          vmSize: Standard_D16s_v3
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: aro_49
            version: 49.84.20211008
          subnet: itzaro-rm5fyd6-worker-subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1
      taints:
        - effect: NoSchedule
          key: node.ocs.openshift.io/storage
          value: "true"